# Generated by Django 6.1 on 2026-08-21 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва країни')),
                ('slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('description', models.TextField(blank=True, verbose_name='Опис країни')),
                ('cover_image', models.ImageField(upload_to='countries/', verbose_name='Обкладинка')),
            ],
            options={
                'verbose_name': 'Країна',
                'verbose_name_plural': 'Країни',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Назва туру')),
                ('slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('description', models.TextField(verbose_name='Короткий опис')),
                ('full_content', models.TextField(blank=True, verbose_name='Повний опис')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tours/covers/', verbose_name='Обкладинка тура')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Тривалість (днів)')),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна від (€)')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Середній'), ('hard', 'Складний'), ('extreme', 'Екстремальний')], default='easy', max_length=20, verbose_name='Складність')),
                ('group_size_max', models.PositiveIntegerField(default=10, verbose_name='Макс. кількість осіб у групі')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.country', verbose_name='Країна')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Тури',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата закінчення')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Точна ціна (€)')),
                ('available_seats', models.PositiveIntegerField(verbose_name='Вільних місць')),
                ('status', models.CharField(choices=[('open', 'Набір відкрито'), ('few_left', 'Залишилося небагато місць'), ('sold_out', 'Місць немає'), ('canceled', 'Скасовано')], default='open', max_length=20, verbose_name='Статус групи')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Дата заїзду',
                'verbose_name_plural': 'Дати заїздів',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/gallery/', verbose_name='Зображення')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Підпис / Alt текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Фотографії з туру',
                'verbose_name_plural': 'Галерея туру',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TourInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Назва послуги')),
                ('is_included', models.BooleanField(default=True, help_text='Входить (галочка), не входить (порожній квадрат)', verbose_name='Входить у вартість')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Включення/Виключення',
                'verbose_name_plural': 'Що входить / не входить',
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='День №')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок дня')),
                ('description', models.TextField(verbose_name='Опис дня')),
                ('accommodation', models.CharField(blank=True, max_length=255, verbose_name='Проживання')),
                ('meals', models.CharField(blank=True, max_length=100, verbose_name='Харчування')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Розклад програми',
                'verbose_name_plural': 'Розклад за днями',
                'ordering': ['day_number'],
                'unique_together': {('tour', 'day_number')},
            },
        ),
    ]
