# Generated by Django 6.1 on 2026-08-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='ISO код'),
        ),
    ]
