# Generated by Django 6.1 on 2026-08-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='ISO код'),
        ),
    ]
