# Generated by Django 6.1 on 2026-10-03 14:58

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_historicaltour_price_from_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltour',
            name='price_from',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10, verbose_name='Ціна від'),
        ),
        migrations.AlterField(
            model_name='historicaltour',
            name='price_from_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('UAH', 'Ukrainian Hryvnia')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicaltourdate',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10, verbose_name='Точна ціна'),
        ),
        migrations.AlterField(
            model_name='historicaltourdate',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('UAH', 'Ukrainian Hryvnia')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_from',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10, verbose_name='Ціна від'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_from_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('UAH', 'Ukrainian Hryvnia')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10, verbose_name='Точна ціна'),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('UAH', 'Ukrainian Hryvnia')], default='EUR', editable=False, max_length=3),
        ),
    ]
