# Generated by Django 6.1 on 2026-09-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'Нове бронювання'), ('confirmed', 'Підтверджено (очікує оплати)'), ('paid', 'Оплачено'), ('completed', 'Завершено'), ('canceled', 'Скасовано')], db_index=True, default='new', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
