# Generated by Django 6.1 on 2026-10-03 14:58

import djmoney.models.fields
import djmoney.money
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_historicalbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('UAH', 'Ukrainian Hryvnia')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='total_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('UAH', 'Ukrainian Hryvnia')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), default_currency='EUR', max_digits=10, verbose_name='Загальна вартість'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='total_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), default_currency='EUR', max_digits=10, verbose_name='Загальна вартість'),
        ),
    ]
